#!/usr/bin/env python3
"""Regression tests for schedule-driven public channel discovery and persistence."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_module(name: str, relative: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / relative)
    if spec is None or spec.loader is None:
        raise AssertionError(f"Could not import {relative}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


catalogue = load_module("update_catalogue_test", "scripts/update-catalogue.py")
discovery = load_module("scheduled_discovery_test", "scripts/discover-scheduled-releases.py")
schedule = json.loads((ROOT / "scheduled-releases.json").read_text(encoding="utf-8"))

assert catalogue.PERSISTENT_DISCOVERY_SOURCE == "scheduled-channel-upload"

mock_existing = {
    "releases": [
        {
            "id": "abcDEF12345",
            "artist": "Zion Daley",
            "title": "Where We Live",
            "group": "Reggae",
            "rawTitle": "Zion Daley - Where We Live | Reggae 2026 | NextGen Sessions",
            "discoverySource": catalogue.PERSISTENT_DISCOVERY_SOURCE,
            "url": "/releases/zion-daley-where-we-live/",
        },
        {
            "id": "ZYX987abc12",
            "artist": "Someone Else",
            "title": "Playlist Only",
            "group": "Reggae",
            "rawTitle": "Someone Else - Playlist Only",
        },
    ]
}

persistent = catalogue.persistent_scheduled_candidates(mock_existing)
assert len(persistent) == 1, f"Expected exactly one persistent schedule-discovered candidate, got {len(persistent)}"
assert persistent[0]["id"] == "abcDEF12345"
assert persistent[0]["artist"] == "Zion Daley"
assert persistent[0]["title"] == "Where We Live"
assert persistent[0]["group"] == "Reggae"
assert persistent[0]["discoverySource"] == catalogue.PERSISTENT_DISCOVERY_SOURCE
assert "url" not in persistent[0], "Derived release URL must be regenerated by render-releases.py"

scheduled = {
    "artist": "Zion Daley",
    "title": "Where We Live",
    "group": "Reggae",
    "releaseLocal": "2026-09-04T18:00:00",
    "timezone": "Europe/London",
    "artistPath": "/artists/zion-daley/",
    "releaseSlug": "zion-daley-where-we-live",
}
discovery.validate_schedule_item(scheduled)

uploads = [
    {
        "snippet": {"title": "Zion Daley - Where We Live | Reggae 2026 | NextGen Sessions"},
        "contentDetails": {"videoId": "abcDEF12345"},
        "status": {"privacyStatus": "public"},
    },
    {
        "snippet": {"title": "Zion Daley - Where We Live | Reggae 2026 | NextGen Sessions"},
        "contentDetails": {"videoId": "private12345"},
        "status": {"privacyStatus": "private"},
    },
    {
        "snippet": {"title": "Zion Daley - Something Else | Reggae 2026 | NextGen Sessions"},
        "contentDetails": {"videoId": "otherID1234"},
        "status": {"privacyStatus": "public"},
    },
]
matched = discovery.matching_uploads([scheduled], uploads)
assert len(matched) == 1, f"Expected one exact public scheduled upload match, got {len(matched)}"
assert matched[0][1] == "abcDEF12345"

for item in schedule.get("releases", []):
    discovery.validate_schedule_item(item)
    assert item.get("group"), f"Scheduled release is missing catalogue group: {item.get('artist')} — {item.get('title')}"

workflow = (ROOT / ".github/workflows/update-catalogue.yml").read_text(encoding="utf-8")
needle_discover = "Discover due scheduled releases from public channel"
needle_render = "Render crawlable release archive and pages"
needle_preserve = "Preserve catalogue timestamp on no-op checks"
assert needle_discover in workflow, "Production workflow must run scheduled channel discovery"
assert workflow.index(needle_discover) < workflow.index(needle_render), "Discovery must run before release rendering"
assert workflow.index(needle_render) < workflow.index(needle_preserve), "No-op timestamp comparison must run after URLs/slugs are regenerated"

print("Scheduled channel discovery validated: exact public matching, durable persistence, workflow ordering and schedule groups are enforced.")
